{% set version = "1.0.1" %}
{% set name = "salty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LanLab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5d65b5ab32012d5d3efc552e513cc00be040d7822de0b07576b6021ed462cd1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - kma >=1.4.9
    - pandas >=1.5.0

about:
  home: https://github.com/LanLab/salty
  license: GPL3
  license_file: LICENSE
  summary: SaLTy assigns a lineage to Staphylococcus aureus WGS data and is suitable for describing large-scale S. aureus genomic epidemiology.

test:
  commands:
    - salty --help
    - salty --version
